version: '3.8'

services:
  app:
    image: currency-converter-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/currency_db
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: pass
    depends_on:
      - postgres
      - flyway
    volumes:
      - .:/app
      - /app/target
    command: mvn spring-boot:run

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: currency_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  flyway:
    image: flyway/flyway
    depends_on:
      - postgres
    volumes:
      - ./src/main/resources/db/migration:/flyway/sql
    command: ["migrate",
              "-url=jdbc:postgresql://postgres:5432/currency_db",
              "-user=admin",
              "-password=pass",
              "-locations=filesystem:/flyway/sql",
              "-connectRetries=60"]

volumes:
  postgres_data: