version: '3'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: admin
      POSTGRES_DB: currency_db
    expose:
      - 5432
    ports:
      - "5432:5432"