#spring.datasource.url=jdbc:postgresql://postgres:5432/currency_db
#spring.datasource.username=admin
#spring.datasource.password=password
#spring.jpa.hibernate.ddl-auto=update

spring:
  datasource:
    driver-class-name: ${DATABASE_DRIVER:org.postgresql.Driver}
    url: ${DATABASE_URL:jdbc:postgresql://:5432/currency_db}
    username: ${DATABASE_USER:admin}
    password: ${DATABASE_PASSWORD:password}
#jpa:
#  hibernate:
#    ddl-auto: update
#  show-sql: true
#  properties:
#    hibernate:
#      dialect: org.hibernate.dialect.PostgreSQLDialect

